### PR TITLE
New features, bug and grammar fixes

### PR DESCRIPTION
**Pull request by Seniru**
Hello! I made some changes to this code. Below are those changes
 - Added new features
   - Added a method start() to start the typing effect
   - Added a width property to the cursor

 - Bug fixes: The cursor doesn't appear as the method that gives that effect isn't called successfully
 - Grammar fixes
 - Updated README

### CODE REVIEW

**Comment by Seniru** [comment]
Waiting for your response @Dob6458

**Comment by Dob6458** [comment]
I will check it...

**Comment by Dob6458** [comment]
Thank you for correction 😉

**Comment by Seniru** [comment]
You are welcome!

**Comment by Dob6458** [comment]
.

**Pull request merged**
